//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGame()
        {
            this.tblOrdergame = new HashSet<tblOrdergame>();
        }
    
        public int gameID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string gameName { get; set; }
        public string gameDescription { get; set; }
        public int gamePrice { get; set; }
        public string gameImage { get; set; }
        public Nullable<int> gameQuantity { get; set; }
        public string gameStatus { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrdergame> tblOrdergame { get; set; }
    }
}
