//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrdergame
    {
        public int ordergameID { get; set; }
        public int orderID { get; set; }
        public int gameID { get; set; }
        public Nullable<int> numOfgame { get; set; }
        public int pricegame { get; set; }
    
        public virtual tblGame tblGame { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
